### ISSUE TITLE
Add other package updates to install process

### ISSUE THREAD

**Issue by electrikjesus** [aditya24raj/install_waydroid#1]
https://github.com/aditya24raj/install_waydroid/blob/57a6a7224c3eb2ec87f16cb66d5ece2b5d00530e/install_waydroid.sh#L63
I think we could add a method that matches the hosts current release name to what is found in https://repo.waydro.id/erfan/* and download all other .deb files except for waydroid itself, then use dpkg -i *.deb to install them (mutter is the main issue here as it is not getting updated with waydroid install)

**Comment by aditya24raj** [comment]
updated the script. it should be able to install packages from https://repo.waydroid.id/erfan/<distro>
